name: Deploy PHP to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload website to InfinityFree
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload files to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
